name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if you choose a different branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Will use Node.js 20 automatically

      - name: Build static files
        id: build
        run: |
          echo "Building static files..."
          mkdir -p pages
          echo "<h1>Hello, GitHub Pages</h1>" > pages/index.html

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: pages/  # Replace with your folder path

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

